#!/bin/bash
echo 'into'
source ~/.bashrc
cyc=$1

mkdir -p ~/gefs/gpfs/dell1/stmp/Alicia.Bentley
mkdir -p ~/gefs/gpfs/dell1/stmp/Alicia.Bentley/gefs
cd ~/gefs/gpfs/dell1/stmp/Alicia.Bentley/gefs


year=`cut -c 1-4 holddate.txt`
month=`cut -c 5-6 holddate.txt`
day=`cut -c 7-8 holddate.txt`
hour=`cut -c 9-10 holddate.txt`
dow=`cut -c 11-13 holddate.txt`
ymdh=${year}${month}${day}${hour}
ymdhdow=${year}${month}${day}${hour}${dow}

python ~/gefs/code/makegefs3qpfcsv.py $ymdh &
python ~/gefs/code/makegefs850tcsv.py $ymdh &
wait

exit


