#! /bin/bash
#
#BSUB -J wafs.ftp
#BSUB -oo /gpfs/dell2/emc/verification/save/Alicia.Bentley/gefs/gefsftp.out
#BSUB -eo /gpfs/dell2/emc/verification/save/Alicia.Bentley/gefs/gefsftp.out
#BSUB -n 1
#BSUB -W 00:10
#BSUB -P GEN-T2O
#BSUB -R "affinity[core]"
#BSUB -q dev_transfer
#BSUB -R "rusage[mem=300]"

set -x

cd ~/gefs/gpfs/dell1/stmp/Alicia.Bentley/gefs

cyc=`cut -c 9-10 holddate.txt`
day=`cut -c 7-8 holddate.txt`
echo $day
number=$(ls -l * | grep csv | wc -l)

pwd

ls -l

ls -l *csv

pwd

#cp *pw*csv /var/www/gefs-plumes.webhop.me/
#cp *850*csv /var/www/gefs-plumes.webhop.me
#cp *cape*csv /var/www/gefs-plumes.webhop.me
#cp *10m*csv /var/www/gefs-plumes.webhop.me
#cp *typ*csv /var/www/gefs-plumes.webhop.me
#cp *snow*csv /var/www/gefs-plumes.webhop.me
find . -name "*pw*csv" -exec cp '{}' /var/www/gefs-plumes.webhop.me \;
find . -name "*850*csv" -exec cp '{}' /var/www/gefs-plumes.webhop.me \;
find . -name "*cape*csv" -exec cp '{}' /var/www/gefs-plumes.webhop.me \;
find . -name "*10m*csv" -exec cp '{}' /var/www/gefs-plumes.webhop.me \;
find . -name "*typ*csv" -exec cp '{}' /var/www/gefs-plumes.webhop.me \;
find . -name "*snow*csv" -exec cp '{}' /var/www/gefs-plumes.webhop.me \;

if [[ $number -gt 3700 ]];then
  cp EMC*html /var/www/gefs-plumes.webhop.me/index.html
fi

exit
