#!/bin/bash

set +x
source ~/.bashrc
set -x

cd ~/gefs/gpfs/dell1/stmp/Alicia.Bentley/gefs
export HOLDIN=~/gefs/gpfs/dell1/stmp/Alicia.Bentley
export GBexec=~/gefs/gpfs/dell1/nco/ops/nwprod/util/exec

echo intoscript
year=`cut -c 1-4 holddate.txt`
month=`cut -c 5-6 holddate.txt`
day=`cut -c 7-8 holddate.txt`
hour=`cut -c 9-10 holddate.txt`
cyc=`cut -c 9-10 holddate.txt`
ymdh=${year}${month}${day}${hour}


set +x
set -x

'rm' poescript3

echo "~/gefs/code/launchgefs3 ${cyc}" >> poescript3


chmod 775 poescript3
export MP_PGMMODEL=mpmd
export MP_CMDFILE=poescript3

echo beforelsf
./poescript3
echo pastlsf

exit
