#! /bin/bash
#
#BSUB -J wafs.ftp
#BSUB -oo /gpfs/dell2/emc/verification/save/Alicia.Bentley/gefs/gefsftp1.out
#BSUB -eo /gpfs/dell2/emc/verification/save/Alicia.Bentley/gefs/gefsftp1.out
#BSUB -n 1
#BSUB -W 00:10
#BSUB -P GEN-T2O
#BSUB -R "affinity[core]"
#BSUB -q dev_transfer
#BSUB -R "rusage[mem=300]"

set -x

cd ~/gefs/gpfs/dell1/stmp/Alicia.Bentley/gefs

cyc=`cut -c 9-10 holddate.txt`
day=`cut -c 7-8 holddate.txt`
echo $day

pwd

ls -l

ls -l *csv

pwd

#scp *2m*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/plumes
#scp *qpf*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/plumes
#scp *shear*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/plumes
#scp *thick*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/plumes
#scp *slp*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/plumes
#scp *rh*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/plumes
cp *2m*csv /var/www/gefs-plumes.webhop.me
cp *qpf*csv /var/www/gefs-plumes.webhop.me
cp *shear*csv /var/www/gefs-plumes.webhop.me
cp *thick*csv /var/www/gefs-plumes.webhop.me
cp *slp*csv /var/www/gefs-plumes.webhop.me
cp *rh*csv /var/www/gefs-plumes.webhop.me

exit
