#!/bin/bash

set +x
source ~/.bashrc
set -x

cd ~/gefs/gpfs/dell1/stmp/Alicia.Bentley/gefs
export HOLDIN=~/gefs/gpfs/dell1/stmp/Alicia.Bentley
export GBexec=~/gefs/gpfs/dell1/nco/ops/nwprod/util/exec

echo intoscript
year=`cut -c 1-4 holddate.txt`
month=`cut -c 5-6 holddate.txt`
day=`cut -c 7-8 holddate.txt`
hour=`cut -c 9-10 holddate.txt`
cyc=`cut -c 9-10 holddate.txt`
ymdh=${year}${month}${day}${hour}


set +x
set -x

'rm' poescript1

echo "~/gefs/code/launchgefs ${cyc}" >> poescript1


chmod 775 poescript1
export MP_PGMMODEL=mpmd
export MP_CMDFILE=poescript1

echo beforelsf
./poescript1
echo pastlsf

~/gefs/code/run_ftp_gefs1
~/gefs/code/run_ftp_gefs
exit
